version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Install dependencies"
      - composer install --no-dev --prefer-dist --no-interaction

  pre_build:
    commands:
      - echo "Run tests"
      - php artisan test || true

      - echo "RELEASE_TAG=$RELEASE_TAG"
      - VERSION=$RELEASE_TAG
      - COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION

  build:
    commands:
      - echo "Set execute permission for scripts"
      - chmod +x scripts/*.sh
      - echo "Build done for version $VERSION"

artifacts:
  name: build-$VERSION
  files:
    - '**/*'
  discard-paths: no
