version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Install dependencies"
      - composer install --no-dev --prefer-dist --no-interaction

  pre_build:
  commands:
    - echo "Detect version info"

    # Git commit (AWS inject)
    - GIT_COMMIT=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}

    # Git tag (nếu build từ tag thì CodePipeline đã biết)
    - GIT_TAG=${CODEBUILD_SOURCE_VERSION:-no-tag}

    # Pipeline metadata
    - PIPELINE_NAME=${CODEPIPELINE_PIPELINE_NAME:-manual}
    - PIPELINE_EXECUTION_ID=${CODEPIPELINE_EXECUTION_ID:-manual}
    - BUILD_ID=$CODEBUILD_BUILD_ID

    - echo "Run tests"
    - php artisan test || true

  build:
    commands:
      - echo "Generate VERSION file"

      - |
        cat <<EOF > VERSION
        APP_NAME=exment
        ENV=PROD

        VERSION=$GIT_TAG
        GIT_TAG=$GIT_TAG
        GIT_COMMIT=$GIT_COMMIT

        PIPELINE_NAME=$PIPELINE_NAME
        PIPELINE_EXECUTION_ID=$PIPELINE_EXECUTION_ID
        BUILD_ID=$BUILD_ID

        DEPLOYED_AT=$(date '+%Y-%m-%d %H:%M:%S')
        EOF

      - echo "Set execute permission for scripts"
      - chmod +x scripts/*.sh
      - echo "Build done"

artifacts:
  files:
    - '**/*'
  discard-paths: no
