version: 0.2

env:
  exported-variables:
    - APP_VERSION

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Install dependencies"
      - composer install --no-dev --prefer-dist --no-interaction

  pre_build:
    commands:
      - echo "Build version: ${APP_VERSION}"
      - echo "tests "
      
  build:
    commands:
      - echo "Build done for version ${APP_VERSION}"
      - chmod +x scripts/*.sh

artifacts:
  name: app-${APP_VERSION}
  files:
    - '**/*'
  discard-paths: no
