version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "Install PHP sodium extension (official way)"

      # install php sodium extension
      - yum update -y
      - yum install -y php-sodium

      # verify
      - php -m | grep sodium || echo "sodium loaded"

      - echo "Install PHP dependencies"
      - composer install --no-dev --prefer-dist --no-interaction

  pre_build:
    commands:
      - echo "Run tests"
      - php artisan test || true

  build:
    commands:
      - echo "Set execute permission for scripts"
      - chmod +x scripts/*.sh
      - echo "Build done"

artifacts:
  files:
    - '**/*'
  discard-paths: no
